Python3
farsightsec/pynmsg pull request #28
Opened 2019-06-05 18:30 UTC by jeffmurphy

Merged: edmunds branch (python3-fixes and nogil) and cisco fork (python3 branch) and then updated, addressed issues like lack of sigint handing, tested against py2 and py3.

2019-10-14 20:53 UTC, alesage commented
Seeing a new warning, any comments @jeffmurphy ?
```
`sig_manager.c:8:12: warning: ‘pynmsg_raise_signal’ used but never defined
 static int pynmsg_raise_signal(int sig);
            ^~~~~~~~~~~~~~~~~~~
```

2019-10-14 21:20 UTC, jeffmurphy commented
maybe remove the attribute ... i dont recall why i tagged it with that attribute

https://github.com/farsightsec/pynmsg/blob/python3/sig_manager.c#L7

2019-10-14 21:35 UTC, alesage commented
No dice :( , any further thoughts welcome. . . .

2019-10-15 02:54 UTC, jeffmurphy commented
Try

```
diff --git a/nmsg_io.pyx b/nmsg_io.pyx
index 71a45b0..382add4 100644
--- a/nmsg_io.pyx
+++ b/nmsg_io.pyx
@@ -28,7 +28,7 @@ def python_check_interrupt(sig, frame):
     global raise_kbint
     raise_kbint = 1
 
-cdef int pynmsg_raise_signal "pynmsg_raise_signal"(int sig) except 0 with gil:
+cdef public int pynmsg_raise_signal "pynmsg_raise_signal"(int sig) except 0 with gil:
     if PyErr_Occurred():
         return 0
     elif sig == SIGINT:
diff --git a/sig_manager.c b/sig_manager.c
index 927dffd..d184e15 100644
--- a/sig_manager.c
+++ b/sig_manager.c
@@ -4,8 +4,7 @@
 #include <string.h>
 #include <Python.h>
 
-__attribute__((unused))
-static int pynmsg_raise_signal(int sig);
+extern int pynmsg_raise_signal(int sig);
 
 static void pynmsg_sighandler(int sig)
 {

```

2020-12-16 18:17 UTC, hstern requested changes
Builds but does not load symbols on macos 10.15.7. Not a blocker for merging.

2020-12-16 18:17 UTC, hstern commented on nmsg_input.pyx
> +def _cstar2str(x):
This looks like a misspelling

2021-01-29 00:48 UTC, alesage commented
Closing this as it's served by the recent merge of Python3 material to master.

2021-01-29 00:48 UTC, closed without merging